from pathlib import Path
from typing import BinaryIO, Protocol


class Storage(Protocol):
    def save(self, source: BinaryIO, key: str) -> str: ...
    def resolve_local_path(self, key: str) -> Path: ...
    def delete(self, key: str) -> None: ...
